spring:
  application:
    name: stickareer

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값 local

server:
  port: 8080

jwt:
  secret: PQNzZrvMR2FDl4LLj3u8zX7fXVo3vJGo
  redirect: http://localhost:8080/login?name=%s&access_token=%s&refresh_token=%s
  access-token:
    expiration-time: 360000
  refresh-token:
    expiration-time: 604800000

---
spring:
  config:
    activate:
      on-profile: local
      
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true

  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: prod
      
  # MySQL 설정
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_HOST}
    password: ${DATABASE_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true

  sql:
    init:
      mode: always

---
# OAuth2 설정 (공통)
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID:4b7a68b48409bc6ea6ce0f9c7459fb6e}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:PQNzZrvMR2FDl4LLj3u8zX7fXVo3vJGo}
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
